
name: Load Env from File

on:
  push:
    branches: [ main ]

jobs:
  
  load-env-vars:
    runs-on: ubuntu-latest
    env:
      filename: file.txt
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Load and export env variables
      run: |

        # set -a
        # source file.txt
        # set +a

        # while IFS='=' read -r key value; do
        #   # Remove quotes from value if any
        #   clean_value=$(echo "$value" | sed "s/^['\"]//;s/['\"]$//")
        #   echo "$key=$clean_value" >> $GITHUB_ENV
        # done < file.txt
        # cat file.txt >> $GITHUB_ENV
        cat $filename >>  $GITHUB_ENV

    - name: Use environment variables
      run: |
        echo "TIMEZONE is $TIMEZONE"
        echo "EMAIL_PASS value is $EMAIL_PASS"
        echo "Total envs loaded!"
